"""empty message

Revision ID: 49ff72ae27fb
Revises: 81efe889d27f
Create Date: 2019-08-06 00:20:03.812759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ff72ae27fb'
down_revision = 'c498fa7d25ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=32)))
    op.execute('UPDATE users SET name="Unknown";')
    op.alter_column('users', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
